//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neos Account Downloader.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the download?.
        /// </summary>
        public static string AreYouSureDownloadCancel {
            get {
                return ResourceManager.GetString("AreYouSureDownloadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Variable Definitions.
        /// </summary>
        public static string CloudVariableDefinitions {
            get {
                return ResourceManager.GetString("CloudVariableDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Variable Values.
        /// </summary>
        public static string CloudVariableValues {
            get {
                return ResourceManager.GetString("CloudVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download is complete, would you like to start another one?.
        /// </summary>
        public static string CompleteQuestion {
            get {
                return ResourceManager.GetString("CompleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While every effort is made to download everything from your account, this utility may miss or lose some data. As such we&apos;re unable to offer any guarentee or warranty on this application&apos;s ability. This is in line with the License but this additional disclaimer is here in the hopes of transparency..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete!.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download is complete. Below is a report detailing some statistics from the download. A copy of this has also been written to a log files.
        /// </summary>
        public static string DownloadCompleteDescription {
            get {
                return ResourceManager.GetString("DownloadCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download failed to aquire some records, you can find their details below, or see the logs for more information..
        /// </summary>
        public static string DownloadCompleteRecordFailureDescription {
            get {
                return ResourceManager.GetString("DownloadCompleteRecordFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate (Items/Worlds per minute).
        /// </summary>
        public static string DownloadRate {
            get {
                return ResourceManager.GetString("DownloadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Report.
        /// </summary>
        public static string DownloadReport {
            get {
                return ResourceManager.GetString("DownloadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank..
        /// </summary>
        public static string Errors_BlankPassword {
            get {
                return ResourceManager.GetString("Errors.BlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank..
        /// </summary>
        public static string Errors_BlankUsername {
            get {
                return ResourceManager.GetString("Errors.BlankUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select folders, please enter one manually..
        /// </summary>
        public static string Errors_CannotSelectFolder {
            get {
                return ResourceManager.GetString("Errors.CannotSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account download cancelled!.
        /// </summary>
        public static string Errors_DownloadCancelled {
            get {
                return ResourceManager.GetString("Errors.DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Download has failed, due to {0}. Please consult the log files for more details and/or try again..
        /// </summary>
        public static string Errors_DownloadFailure {
            get {
                return ResourceManager.GetString("Errors.DownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected..
        /// </summary>
        public static string Errors_NoFolderSelected {
            get {
                return ResourceManager.GetString("Errors.NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate main window..
        /// </summary>
        public static string Errors_NoMainWindow {
            get {
                return ResourceManager.GetString("Errors.NoMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while logging in..
        /// </summary>
        public static string Errors_UnexpectedLoginError {
            get {
                return ResourceManager.GetString("Errors.UnexpectedLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string Errors_UnknownError {
            get {
                return ResourceManager.GetString("Errors.UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Reason.
        /// </summary>
        public static string FailureReason {
            get {
                return ResourceManager.GetString("FailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool aims to download your entire Neos account contents. Depending on how much content your account contains, this may take a while. Please try not to interrupt this process, once it has started. Just leave it running until it lets you know it is complete..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (admin).
        /// </summary>
        public static string GroupsAdminIndicator {
            get {
                return ResourceManager.GetString("GroupsAdminIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which group&apos;s content should we download?.
        /// </summary>
        public static string GroupsQuestion {
            get {
                return ResourceManager.GetString("GroupsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &amp; Worlds.
        /// </summary>
        public static string InventoryWorlds {
            get {
                return ResourceManager.GetString("InventoryWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to your Neos account..
        /// </summary>
        public static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message History.
        /// </summary>
        public static string MessageHistory {
            get {
                return ResourceManager.GetString("MessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Groups found..
        /// </summary>
        public static string NoGroupsFound {
            get {
                return ResourceManager.GetString("NoGroupsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open folder..
        /// </summary>
        public static string OpenFolder_Failed {
            get {
                return ResourceManager.GetString("OpenFolder_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening a folder is unsupported on this platform. You can manually navigate to the folder at: {0}.
        /// </summary>
        public static string OpenFolder_UnsupportedPlatform {
            get {
                return ResourceManager.GetString("OpenFolder_UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your one-time password from your authenticator app..
        /// </summary>
        public static string OTPPrompt {
            get {
                return ResourceManager.GetString("OTPPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time password.
        /// </summary>
        public static string OTPWatermark {
            get {
                return ResourceManager.GetString("OTPWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ID.
        /// </summary>
        public static string RecordId {
            get {
                return ResourceManager.GetString("RecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Path.
        /// </summary>
        public static string RecordPath {
            get {
                return ResourceManager.GetString("RecordPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download.
        /// </summary>
        public static string StartDownload {
            get {
                return ResourceManager.GetString("StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download will require at least {0} in file space..
        /// </summary>
        public static string StorageRequired {
            get {
                return ResourceManager.GetString("StorageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Metadata.
        /// </summary>
        public static string UserMetadata {
            get {
                return ResourceManager.GetString("UserMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Records.
        /// </summary>
        public static string UserRecords {
            get {
                return ResourceManager.GetString("UserRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to Download?.
        /// </summary>
        public static string WhatDownload {
            get {
                return ResourceManager.GetString("WhatDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you like to download it to?.
        /// </summary>
        public static string WhereDownload {
            get {
                return ResourceManager.GetString("WhereDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to start another download?.
        /// </summary>
        public static string WouldYouLikeToStartAnotherDownload {
            get {
                return ResourceManager.GetString("WouldYouLikeToStartAnotherDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
