name: Security Scan
on:
  schedule:
    - cron: '20 14 * * 1'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  build:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp
    - name: Restore Neos DLL Cache
      id: cache-neos-dlls
      uses: actions/cache/restore@v3
      with:
        path: |
          ExternalLibraries/BaseX.dll
          ExternalLibraries/CloudX.Shared.dll
          ExternalLibraries/CodeX.dll
        key: neos-dlls
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:csharp"
