name: Security Scan
on:
  schedule:
    - cron: '20 14 * * 1'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  build:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - name: Setup .NET 7
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: 7.0.x
    - name: Initialize CodeQL
      uses: github/codeql-action/init@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # v2.21.5
      with:
        languages: csharp
    - name: Restore Neos DLL Cache
      id: cache-neos-dlls
      uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: |
          ExternalLibraries/BaseX.dll
          ExternalLibraries/CloudX.Shared.dll
          ExternalLibraries/CodeX.dll
        key: neos-dlls
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # v2.21.5
      with:
        category: "/language:csharp"
