name: Security Scan
on:
  schedule:
    - cron: '20 14 * * 1'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  build:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: 7.0.x
    - name: Initialize CodeQL
      uses: github/codeql-action/init@a09933a12a80f87b87005513f0abb1494c27a716 # v2.21.4
      with:
        languages: csharp
    - name: Restore Neos DLL Cache
      id: cache-neos-dlls
      uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: |
          ExternalLibraries/BaseX.dll
          ExternalLibraries/CloudX.Shared.dll
          ExternalLibraries/CodeX.dll
        key: neos-dlls
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@a09933a12a80f87b87005513f0abb1494c27a716 # v2.21.4
      with:
        category: "/language:csharp"
